services:
  - type: web
    name: instagram-reel-bot
    env: python
    region: oregon
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
    healthCheckPath: /
